# Quiz 1

In [76]:
import pandas as pd
import numpy as np

In [77]:
list_df = pd.read_html('https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M')

In [78]:
type(list_df)

list

In [79]:
df=list_df[0]
df

,Postal code,Borough,Neighborhood
0,M1A,Not assigned,NaN
1,M2A,Not assigned,NaN
2,M3A,North York,Parkwoods
3,M4A,North York,Victoria Village
4,M5A,Downtown Toronto,Regent Park / Harbourfront
...,...,...,...
175,M5Z,Not assigned,NaN
176,M6Z,Not assigned,NaN
177,M7Z,Not assigned,NaN
178,M8Z,Etobicoke,Mimico NW / The Queensway West / South of Bloo...
179,M9Z,Not assigned,NaN

In [80]:
df=df.rename({"Postal code":"PostalCode"},axis=1)
df=df[df["Borough"]!='Not assigned']
df

,PostalCode,Borough,Neighborhood
2,M3A,North York,Parkwoods
3,M4A,North York,Victoria Village
4,M5A,Downtown Toronto,Regent Park / Harbourfront
5,M6A,North York,Lawrence Manor / Lawrence Heights
6,M7A,Downtown Toronto,Queen's Park / Ontario Provincial Government
...,...,...,...
160,M8X,Etobicoke,The Kingsway / Montgomery Road / Old Mill North
165,M4Y,Downtown Toronto,Church and Wellesley
168,M7Y,East Toronto,Business reply mail Processing CentrE
169,M8Y,Etobicoke,Old Mill South / King's Mill Park / Sunnylea /...
178,M8Z,Etobicoke,Mimico NW / The Queensway West / South of Bloo...

In [81]:
df["PostalCode"].value_counts()

M6L    1
M9B    1
M1R    1
M5P    1
M1X    1
      ..
M1M    1
M5X    1
M1C    1
M2K    1
M8Y    1
Name: PostalCode, Length: 103, dtype: int64

In [90]:
new_index = np.arange(0,103)
df[""]=new_index
df=df.set_index("")

In [91]:
df[df["Neighborhood"]=='Not assigned']

Empty DataFrame
Columns: [PostalCode, Borough, Neighborhood]
Index: []

In [92]:
#for i in range(103):
    #for j in range(len(df.iloc[i,2])):
        #if df.iloc[i,2][j-1]=="/":
            #df.iloc[i,2][j]=
            
df["Neighborhood"]=df["Neighborhood"].str.replace("/",",")
df

,PostalCode,Borough,Neighborhood
,,,
0,M3A,North York,Parkwoods
1,M4A,North York,Victoria Village
2,M5A,Downtown Toronto,"Regent Park , Harbourfront"
3,M6A,North York,"Lawrence Manor , Lawrence Heights"
4,M7A,Downtown Toronto,"Queen's Park , Ontario Provincial Government"
...,...,...,...
98,M8X,Etobicoke,"The Kingsway , Montgomery Road , Old Mill North"
99,M4Y,Downtown Toronto,Church and Wellesley
100,M7Y,East Toronto,Business reply mail Processing CentrE
101,M8Y,Etobicoke,"Old Mill South , King's Mill Park , Sunnylea ,..."
102,M8Z,Etobicoke,"Mimico NW , The Queensway West , South of Bloo..."

In [93]:
df.shape

(103, 3)

# Quiz 2

In [100]:
df_geo=pd.read_csv("Geospatial_Coordinates.csv")
df_geo=df_geo.rename({"Postal Code":"PostalCode"},axis=1)
df_geo.dtypes

PostalCode     object
Latitude      float64
Longitude     float64
dtype: object

In [101]:
df.dtypes

PostalCode      object
Borough         object
Neighborhood    object
dtype: object

In [108]:
df_new=df.merge(df_geo, left_on='PostalCode', right_on='PostalCode')
df_new

,PostalCode,Borough,Neighborhood,Latitude,Longitude
0,M3A,North York,Parkwoods,43.753259,-79.329656
1,M4A,North York,Victoria Village,43.725882,-79.315572
2,M5A,Downtown Toronto,"Regent Park , Harbourfront",43.654260,-79.360636
3,M6A,North York,"Lawrence Manor , Lawrence Heights",43.718518,-79.464763
4,M7A,Downtown Toronto,"Queen's Park , Ontario Provincial Government",43.662301,-79.389494
...,...,...,...,...,...
98,M8X,Etobicoke,"The Kingsway , Montgomery Road , Old Mill North",43.653654,-79.506944
99,M4Y,Downtown Toronto,Church and Wellesley,43.665860,-79.383160
100,M7Y,East Toronto,Business reply mail Processing CentrE,43.662744,-79.321558
101,M8Y,Etobicoke,"Old Mill South , King's Mill Park , Sunnylea ,...",43.636258,-79.498509
102,M8Z,Etobicoke,"Mimico NW , The Queensway West , South of Bloo...",43.628841,-79.520999